name: Flask Deployment

on:
  push:
    branches: [ main ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Deploy to EC2 🚀
    
    steps: 
    - name: Deploy in EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST_NAME: ${{ secrets.EC2_HOST }}
        USER_NAME: ${{ secrets.USER_NAME }}
      
      run:
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME}
        ls &&
        cd apps/ &&
        ls &&
        cadastro-clientes/ &&
        git pull origin main &&
        sudo systemctl stop cadastroapp.service &&
        sudo systemctl daemon-reload &&
        sudo systemctl start cadastroapp.service




