name: Flask Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to EC2 🚀
    
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create private key file
      run: echo "${{ secrets.EC2_SSH_KEY }}" > private_key

    - name: Set permissions for private key file
      run: chmod 600 private_key

    - name: Check private_key
      run: cat private_key
      
    - name: Deploy in EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST_NAME: ${{ secrets.EC2_HOST }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        chmod 600 ${PRIVATE_KEY} &&
        ssh -i ${PRIVATE_KEY} ${USER_NAME}@${HOST_NAME} &&
        cd .~/app &&
        ls

