name: Flask Deployment

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2 🚀
    runs-on: ubuntu-latest
    
    steps: 
  
    - name: Deploy in EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST_NAME: ${{ secrets.EC2_HOST }}
        USER_NAME: ${{ secrets.EC2_USERNAME }}
        
      run: |  
        echo "$PRIVATE_KEY " > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key $USER_NAME@$HOST_NAME "
        ls &&
        cd apps/ &&
        ls && 
        cd cadastro-clientes/ &&
        git pull origin main &&
        sudo systemctl restart cadastroapp.service"
        
