name: Flask Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to EC2 🚀
    
    steps: 
    - name: Create private key file
      run: echo "${{ secrets.EC2_SSH_KEY }}" > private_key

    - name: Set permissions for private key file
      run: chmod 600 private_key
      
    - name: Deploy in EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST_NAME: ${{ secrets.EC2_HOST }}
        USER_NAME: ${{ secrets.USER_NAME }}
      
      run: |
        ssh -i private_key ${USER_NAME}@${HOST_NAME} 'cd apps/cadastro-clientes && source venv/bin/activate && pip install -r requirements.txt && git pull origin main && sudo systemctl stop cadastroapp.service && sudo systemctl daemon-reload && sudo systemctl start cadastroapp.service'

